export const API_ENDPOINTS = {
  forgetPassword: "/auth/forgot-password",
  googleOauth: "/auth/google",
  googleCallback: "/auth/google/callback",
  resetPassword: "/auth/reset-password",
  signup: "/auth/signup",
  login: "/auth/login",
  emailverify: "/auth/verify",
  resendemail: "/auth/resend-verification",
  posts: "/posts",
  users: "/users",
  notification: "/notifications",
  userReactions: "/users/reactions",
  userShare: "/users/shares",
  adminUsers: "/admin/users",
  reactions: "/reactions",
  bookmark: "/bookmarks",
  categories: "/admin/categories",
  tags: "/admin/tags",
  avatar: "/images/upload/avatar",
  userCover: "/images/upload/userCover",
  blogCover: "/images/upload/blogCover",
  blogGallery: "/images/upload/gallery/blogGallery",
  adminDashboard: "/admin/dashboard",
  adminBlogs: "/admin/posts",
  commentsByPost: (postId: string) => `/comments/${postId}`,
};
